### ISSUE TITLE
buffer array should be unsigned int

### ISSUE THREAD

**Issue by halicek** [ControlEverythingCom/SHT30#1]
Hi, I was porting your code to Attiny85. Strangely humidity about 49 and higher has returned negative values. After reading the SHT30 datasheet i noticed the sensor sends **unsigned integer** results of measuring. But your code saves this to the signed int array. After the computation, the result can be negative for higher humidity.

**Comment by telliottosceola** [comment]
Nice catch.  I will see to it that the value is displayed as an unsigned int.  Did that correct the problem when you changed that?

Check out our new online store at https://store.ncd.io

Thank you,

Travis Elliott
National Control Devices
430 Market St
Osceola Mo 64776
417 646 5644
travis@controlanything.com

**Comment by halicek** [comment]
Yes, humidity readings now work fine.

**Comment by telliottosceola** [comment]
I just updated the SHT30.h file and changed the buffer object to an unsigned int.  Thank you for pointing this out.  I had never tested the library for humidity readings so I guess I just got lucky in my testing and never had an error.

**Comment by halicek** [comment]
Thanks. As I only use your code btu not whole library, I cannot test it. But it should be enough to close this issue.
